In [8]:
import sys
!{sys.executable} -m pip install duckdb

import duckdb

con = duckdb.connect()
con.sql("CREATE TABLE sales AS SELECT * FROM 'ecommerce_sales_34500.csv'")

Requirement already satisfied: duckdb in /opt/anaconda3/lib/python3.12/site-packages (1.5.5)

In [7]:
con.sql("""
        SELECT * 
        FROM sales 
        LIMIT 10
    """).df()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4,West,False,139.47,7.88,31.17,60,Female
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6,South,False,24.73,4.60,-2.62,37,Male
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4,North,False,166.80,6.58,13.44,34,Male
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6,South,False,63.67,5.50,2.14,21,Female
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6,East,False,13.88,2.74,1.15,39,Male
5,O100005,C15191,P214062,Beauty,53.91,0.10,2,Credit Card,2024-04-14,5,South,False,97.04,6.32,37.35,35,Female
6,O100006,C13772,P201363,Electronics,266.50,0.00,1,PayPal,2025-05-20,5,East,False,266.50,9.10,22.88,49,Male
7,O100007,C13092,P216691,Beauty,9.98,0.00,1,Credit Card,2023-09-14,4,West,False,9.98,4.51,-0.02,66,Other
8,O100008,C15734,P202751,Fashion,6.61,0.05,1,Debit Card,2023-10-23,6,West,False,6.28,3.43,-1.23,37,Female
9,O100009,C16265,P207782,Grocery,10.91,0.00,1,Credit Card,2023-10-31,6,South,False,10.91,2.76,-1.89,56,Male

In [14]:
con.sql("""
        SUMMARIZE sales
    """).df()

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,order_id,VARCHAR,O100000,O134499,35862,None,None,None,None,None,34500,0.0
1,customer_id,VARCHAR,C10000,C17999,7988,None,None,None,None,None,34500,0.0
2,product_id,VARCHAR,P200000,P249999,29131,None,None,None,None,None,34500,0.0
3,category,VARCHAR,Beauty,Toys,7,None,None,None,None,None,34500,0.0
4,price,DOUBLE,1.01,2930.47,14420,119.39163246376822,195.62047655545382,16.701289991781398,45.72845848141611,131.1801390470903,34500,0.0
5,discount,DOUBLE,0.0,0.3,5,0.04929130434782045,0.06989434212559706,0.0,0.0,0.1,34500,0.0
6,quantity,BIGINT,1,5,5,1.4907246376811594,0.9322701140518785,1,1,2,34500,0.0
7,payment_method,VARCHAR,COD,Wallet,6,None,None,None,None,None,34500,0.0
8,order_date,DATE,2023-09-12,2025-09-11,656,2024-09-13 13:39:17.843478,None,2024-03-14,2024-09-16,2025-03-16,34500,0.0
9,delivery_time_days,BIGINT,3,13,11,4.814202898550724,1.2421414829351112,4,5,6,34500,0.0
10,region,VARCHAR,Central,West,5,None,None,None,None,None,34500,0.0
11,returned,BOOLEAN,false,true,2,None,None,None,None,None,34500,0.0
12,total_amount,DOUBLE,0.82,12931.8,13612,170.00849420289833,357.50301441532747,19.731032991236336,56.85970308867415,168.7169064282352,34500,0.0
13,shipping_cost,DOUBLE,0.0,15.65,1355,6.15211971014492,2.3895387280352973,4.424016921169832,6.092291106349172,7.8253198817992775,34500,0.0
14,profit_margin,DOUBLE,-6.2,1536.17,7564,28.11650463768134,53.35294659081037,1.5010754078592996,10.555631820963523,33.06774829170339,34500,0.0
15,customer_age,BIGINT,18,69,47,43.474376811594205,14.980682024232674,30,43,57,34500,0.0
16,customer_gender,VARCHAR,Female,Other,3,None,None,None,None,None,34500,0.0